language: node_js
node_js:
  - "6"
  - "5"
  - "4"
addons:
  apt:
    packages:
      - libdbus-1-dev
      - libglib2.0-dev
      - libexpat1-dev
dist: trusty # precise has expat v2.0, need v2.1
sudo: required # Needed for trusty
script: dbus-launch npm test
